/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/


// src/local-vector/embedding-worker-protocol.ts
function encodeMessage(msg) {
  return JSON.stringify(msg) + "\n";
}
function decodeMessage(line) {
  const trimmed = line.trim();
  if (!trimmed)
    return null;
  try {
    return JSON.parse(trimmed);
  } catch {
    return null;
  }
}

// src/local-vector/embedding-worker.ts
var extractor = null;
var currentModelId = "";
function logError(message, err) {
  console.error(`[AnalogyWorker] ${message}`, err instanceof Error ? err.message : "");
}
async function handleInitialize(req) {
  try {
    const transformers = require("@huggingface/transformers");
    if (req.modelHost) {
      transformers.env.remoteHost = req.modelHost;
      transformers.env.remotePathTemplate = "{model}/resolve/{revision}/";
    }
    transformers.env.cacheDir = req.cacheDir;
    extractor = await transformers.pipeline("feature-extraction", req.modelId, {
      dtype: req.dtype || "q8",
      cache_dir: req.cacheDir
    });
    currentModelId = req.modelId;
    return { id: req.id, ok: true };
  } catch (err) {
    logError("initialize failed", err);
    return {
      id: req.id,
      ok: false,
      error: { code: "WORKER_INIT_FAILED", message: err.message }
    };
  }
}
async function handleEmbed(req) {
  if (!extractor) {
    return {
      id: req.id,
      ok: false,
      error: { code: "WORKER_NOT_INITIALIZED", message: "Worker not initialized" }
    };
  }
  try {
    const output = await extractor(req.texts, { pooling: "mean", normalize: true });
    const dims = output.dims ?? [req.texts.length, output.data.length / req.texts.length];
    const [batch, dim] = dims;
    const embeddings = [];
    for (let i = 0; i < batch; i++) {
      const row = [];
      for (let j = 0; j < dim; j++) {
        row.push(output.data[i * dim + j]);
      }
      embeddings.push(row);
    }
    return { id: req.id, ok: true, embeddings, memoryUsage: getMemoryUsage() };
  } catch (err) {
    logError("embed failed", err);
    return {
      id: req.id,
      ok: false,
      error: { code: "WORKER_EMBED_FAILED", message: err.message }
    };
  }
}
async function handleDispose(req) {
  try {
    if (extractor && typeof extractor.dispose === "function") {
      await extractor.dispose();
    }
  } catch (err) {
    logError("dispose failed", err);
  }
  extractor = null;
  currentModelId = "";
  return { id: req.id, ok: true };
}
function handleHealth(req) {
  return { id: req.id, ok: true, memoryUsage: getMemoryUsage() };
}
function getMemoryUsage() {
  const mu = process.memoryUsage();
  return {
    rss: Math.round(mu.rss / 1024 / 1024),
    heapUsed: Math.round(mu.heapUsed / 1024 / 1024),
    external: Math.round(mu.external / 1024 / 1024)
  };
}
async function handleRequest(req) {
  switch (req.type) {
    case "initialize":
      return handleInitialize(req);
    case "embed":
      return handleEmbed(req);
    case "dispose":
      return handleDispose(req);
    case "health":
      return handleHealth(req);
    default:
      return {
        id: req.id || "unknown",
        ok: false,
        error: { code: "WORKER_UNKNOWN_TYPE", message: "Unknown request type" }
      };
  }
}
var buffer = "";
process.stdin.setEncoding("utf-8");
process.stdin.on("data", async (chunk) => {
  buffer += chunk;
  let lines = buffer.split("\n");
  buffer = lines.pop() || "";
  for (const line of lines) {
    const req = decodeMessage(line);
    if (!req)
      continue;
    const response = await handleRequest(req);
    process.stdout.write(encodeMessage(response));
  }
});
process.stdin.on("end", () => {
  if (buffer.trim()) {
    const req = decodeMessage(buffer);
    if (req) {
      handleRequest(req).then((response) => {
        process.stdout.write(encodeMessage(response));
        process.exit(0);
      });
      return;
    }
  }
  process.exit(0);
});
process.on("uncaughtException", (err) => {
  logError("uncaughtException", err);
  process.exit(1);
});
