import type { EmbeddingRuntimeVersions, RuntimeAsset } from "./runtime-types";

// Generated by scripts/generate-runtime-manifest.mjs from a complete, cryptographically native-attested CI matrix.
export const EMBEDDING_RUNTIME_MANIFEST_SOURCE = "published" as const;
export const EMBEDDING_RUNTIME_PUBLIC_MANIFEST_SHA256 = "4aa284c62e53c2f424e5d32ddad657ec3470eb18b24dd7b52636cb255f3b928d" as const;
export const EMBEDDING_RUNTIME_BUILD_BINDING = "ANALOGY_EMBEDDING_RUNTIME_MANIFEST_SHA256:4aa284c62e53c2f424e5d32ddad657ec3470eb18b24dd7b52636cb255f3b928d" as const;
export const EMBEDDING_RUNTIME_VERSIONS: EmbeddingRuntimeVersions = {
  "node": "22.23.2",
  "transformers": "4.2.0",
  "onnxruntime": "1.26.0"
};

export const GENERATED_EMBEDDING_RUNTIME_ASSETS: RuntimeAsset[] = [
  {
    "id": "embedding-runtime-node22-v1-darwin-arm64",
    "kind": "embedding-runtime",
    "platform": "darwin-arm64",
    "version": "node22-v1",
    "url": "https://github.com/liaocaoxuezhe/obsidian-extension/releases/download/runtime-node22-v1/analogy-embedding-runtime-node22-v1-darwin-arm64.tar.gz",
    "fileName": "analogy-embedding-runtime-node22-v1-darwin-arm64.tar.gz",
    "archive": "tar.gz",
    "size": 59838882,
    "sha256": "a9564a5d4be68c37b2830eb6c584f8ca95d2a78eab45c07947d90aba9a3ade91",
    "executableRelativePath": "analogy-embedding-runtime-node22-v1/node/bin/node",
    "licenseName": "See bundled THIRD_PARTY_NOTICES.txt",
    "licenseUrl": "https://github.com/liaocaoxuezhe/obsidian-extension/releases/download/runtime-node22-v1/analogy-embedding-runtime-node22-v1-darwin-arm64.tar.gz.THIRD_PARTY_NOTICES.txt",
    "source": "published",
    "runtimeVersions": {
      "node": "22.23.2",
      "transformers": "4.2.0",
      "onnxruntime": "1.26.0"
    },
    "internalManifestSha256": "1cf006a8b71333513c9a00d083bc98b38ca9a20c32099b12c649e46a2b70343a"
  },
  {
    "id": "embedding-runtime-node22-v1-win32-x64",
    "kind": "embedding-runtime",
    "platform": "win32-x64",
    "version": "node22-v1",
    "url": "https://github.com/liaocaoxuezhe/obsidian-extension/releases/download/runtime-node22-v1/analogy-embedding-runtime-node22-v1-win32-x64.zip",
    "fileName": "analogy-embedding-runtime-node22-v1-win32-x64.zip",
    "archive": "zip",
    "size": 153388116,
    "sha256": "43f45a5274dd017abafa77ad5ade36d7be87070c1be05e78c6b765073bfa4aa1",
    "executableRelativePath": "analogy-embedding-runtime-node22-v1/node/bin/node.exe",
    "licenseName": "See bundled THIRD_PARTY_NOTICES.txt",
    "licenseUrl": "https://github.com/liaocaoxuezhe/obsidian-extension/releases/download/runtime-node22-v1/analogy-embedding-runtime-node22-v1-win32-x64.zip.THIRD_PARTY_NOTICES.txt",
    "source": "published",
    "runtimeVersions": {
      "node": "22.23.2",
      "transformers": "4.2.0",
      "onnxruntime": "1.26.0"
    },
    "internalManifestSha256": "18d035b832028d144d76267f374bf5468ccc4a3ea90f728541cb26da7a1d88b5"
  }
];
